### ISSUE TITLE
Whether to support script calls to modify the assembly

### ISSUE THREAD

**Issue by DerZc** [gaasedelen/patching#6]
I want to develop another IDA plugins and call pathcing api in other plugins to modify the assembly code, does patching support this operation?

**Comment by gaasedelen** [comment]
In theory, yes you should be able to call into the patching plugin from other plugins. At least, you should always be able to run snippets or one-time scripts within IDA that use the plugin pretty easily.

You should only ever call functions in the 'plugin api' section (these are what I consider 'public' or safe for others to use). It's this highlighted section of core.py: https://github.com/gaasedelen/patching/blob/5a8c62156e9aa0260d915fe946e423b97971b841/plugins/patching/core.py#L292-L575

You can test calling into the plugin in your IDA console, for example try:

```
patching.core.nop_item(here())
```

If you want to access the patching plugin in your own dedicated, installed plugin, it should also be possible. But your plugin will have to get loaded by IDA after the patching plugin is loaded. There should be a few ways to influence plugin loading/ordering via the IDA API iirc, otherwise I think IDA loads plugins alphabetically (?) so you could play with your plugin naming.
